# Generated by Django 3.0.6 on 2020-05-20 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bors', '0004_auto_20200520_1217'),
    ]

    operations = [
        migrations.AlterField(
            model_name='twit',
            name='description',
            field=models.TextField(),
        ),
    ]
