# Generated by Django 3.0.6 on 2020-05-26 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bors', '0011_company_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='status',
            field=models.IntegerField(choices=[(0, 'None'), (1, 'RegisterUser'), (2, 'AllUser')], default=2),
        ),
    ]
