# Generated by Django 3.0.6 on 2020-05-26 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bors', '0012_auto_20200526_0829'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='status_show',
            field=models.IntegerField(choices=[(0, 'None'), (1, 'RegisterUser'), (2, 'AllUser')], default=2),
        ),
        migrations.AlterField(
            model_name='company',
            name='status',
            field=models.IntegerField(choices=[(0, 'DisActive'), (1, 'Active')], default=1),
        ),
    ]
