# Generated by Django 3.0.6 on 2020-06-29 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bors', '0014_auto_20200605_1558'),
    ]

    operations = [
        migrations.AlterField(
            model_name='twit',
            name='status',
            field=models.IntegerField(choices=[(0, 'Draft'), (1, 'Publish')], default=1),
        ),
    ]
