# Generated by Django 3.0.6 on 2020-05-19 20:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=500)),
                ('description', models.CharField(max_length=1000)),
                ('image', models.ImageField(upload_to=None)),
            ],
            options={
                'verbose_name': 'Category',
                'verbose_name_plural': 'Categoreis',
            },
        ),
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('owner', models.CharField(max_length=500)),
                ('name', models.CharField(max_length=500)),
                ('telegram_url', models.CharField(blank=True, max_length=500, null=True)),
                ('description', models.CharField(max_length=1000)),
                ('slug', models.SlugField()),
            ],
        ),
        migrations.CreateModel(
            name='Twit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=1000)),
                ('title', models.CharField(blank=True, max_length=100, null=True)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('avaiable', models.BooleanField(verbose_name=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bors.Category')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bors.Company')),
            ],
            options={
                'verbose_name': 'Twit',
                'verbose_name_plural': 'Twits',
            },
        ),
    ]
