# Generated by Django 3.0.6 on 2020-05-19 21:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bors', '0002_auto_20200519_2059'),
    ]

    operations = [
        migrations.AlterField(
            model_name='twit',
            name='avaiable',
            field=models.BooleanField(default=True),
        ),
    ]
