# Generated by Django 3.0.6 on 2020-05-20 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bors', '0003_auto_20200519_2102'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='twit',
            options={'ordering': ['-created_on'], 'verbose_name': 'Twit', 'verbose_name_plural': 'Twits'},
        ),
        migrations.RenameField(
            model_name='twit',
            old_name='created_date',
            new_name='created_on',
        ),
        migrations.AddField(
            model_name='twit',
            name='status',
            field=models.IntegerField(choices=[(0, 'Draft'), (1, 'Publish')], default=1),
        ),
        migrations.AddField(
            model_name='twit',
            name='updated_on',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
