# Generated by Django 3.0.6 on 2020-05-25 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bors', '0009_auto_20200525_1249'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='category'),
        ),
        migrations.AlterField(
            model_name='twit',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='twit'),
        ),
    ]
