# Generated by Django 3.0.6 on 2020-05-26 08:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bors', '0010_auto_20200525_1252'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='status',
            field=models.IntegerField(choices=[(0, 'DisActive'), (1, 'Active')], default=1),
        ),
    ]
