# Generated by Django 3.0.6 on 2020-06-05 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bors', '0013_auto_20200526_1356'),
    ]

    operations = [
        migrations.AlterField(
            model_name='twit',
            name='status',
            field=models.IntegerField(choices=[('0', 'Draft'), ('1', 'Publish')], default=1),
        ),
    ]
